--DROP TABLE IF EXISTS Ranks CASCADE;
--DROP TABLE IF EXISTS Athletes CASCADE;
--DROP TABLE IF EXISTS Teams CASCADE;
--DROP TABLE IF EXISTS Nationalities CASCADE;
--DROP TABLE IF EXISTS Officials CASCADE; 
--DROP TABLE IF EXISTS Competitions CASCADE;
--DROP TABLE IF EXISTS Venues CASCADE;
--DROP TABLE IF EXISTS TeamComp CASCADE;

CREATE EXTENSION btree_gist;

CREATE TABLE Nationalities (
	countryId INT PRIMARY KEY,
	country VARCHAR(20) NOT NULL);

CREATE TABLE Venues (
	venueId INT PRIMARY KEY,
	venueName VARCHAR(50) NOT NULL, 
	address VARCHAR(50) NOT NULL, 
	zipcode CHAR(5) NOT NULL, 
	city VARCHAR(20) NOT NULL);

CREATE TABLE Officials (
	officialId INT PRIMARY KEY,
	fname VARCHAR(20) NOT NULL,
	lname VARCHAR(20) NOT NULL);

CREATE TABLE Competitions (
	compId INT PRIMARY KEY,
	compName VARCHAR(255) NOT NULL,
	genderClass VARCHAR(10) NOT NULL,
	round VARCHAR(20) NOT NULL,
	officialId INT,
	location INT,
	start_time TIMESTAMP NOT NULL,
	end_time TIMESTAMP NOT NULL,
	FOREIGN KEY (officialId) REFERENCES Officials(officialId) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (location) REFERENCES Venues(venueId) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT event_time_and_place EXCLUDE USING gist (location WITH =, tsrange(start_time, end_time, '[]') WITH &&));


CREATE TABLE Teams (
	teamId INT PRIMARY KEY,
	compId INT,
	countryId INT,
	sport VARCHAR(20) NOT NULL,
	FOREIGN KEY (countryId) REFERENCES Nationalities(countryId)ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (compId) REFERENCES Competitions(compId) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE TeamComp (
	compId INT REFERENCES Competitions(compId) ON UPDATE CASCADE ON DELETE CASCADE,
	teamId INT REFERENCES Teams(teamId) ON UPDATE CASCADE ON DELETE CASCADE);
